apiVersion: v1
kind: Service
metadata:
  name: spring-apache-kafka-consumer
  namespace: spring-apache-kafka
  labels:
    name: spring-apache-kafka-consumer
    app: spring-apache-kafka-consumer
spec:
  type: NodePort
  ports:
    - port: 8106
      targetPort: 8106
      nodePort: 30106
  selector:
    name: spring-apache-kafka-consumer
    app: spring-apache-kafka-consumer