apiVersion: v1
kind: Service
metadata:
  name: spring-apache-kafka-producer
  namespace: spring-apache-kafka
  labels:
    name: spring-apache-kafka-producer
    app: spring-apache-kafka-producer
spec:
  type: NodePort
  ports:
    - port: 8105
      targetPort: 8105
      nodePort: 30105
  selector:
    name: spring-apache-kafka-producer
    app: spring-apache-kafka-producer