apiVersion: v1
kind: Service
metadata:
  name: apache-kafka
  namespace: spring-apache-kafka
spec:
  ports:
    - port: 9092
      name: broker
    - port: 9093
      name: controller
  clusterIP: None
  selector:
    app: apache-kafka