apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-apache-kafka-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com/spring-apache-kafka-org/k8s-spring-apache-kafka.git
    targetRevision: HEAD
    path: spring-apache-kafka/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
