apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret-github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "git"
  url: "git@github.com:spring-apache-kafka-org/k8s-spring-apache-kafka.git"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDyFp5qfRhVWUj1yOxOwcX07SQCpaIL+viEb0lVHQEBIwAAAKg1XWbONV1m
    zgAAAAtzc2gtZWQyNTUxOQAAACDyFp5qfRhVWUj1yOxOwcX07SQCpaIL+viEb0lVHQEBIw
    AAAEAMGcFdpRahFQv+guZ6gojKot3N44sUzUfsGX9niUHh0fIWnmp9GFVZSPXI7E7BxfTt
    JAKlogv6+IRvSVUdAQEjAAAAImlkX2VkMjU1MTlfc3ByaW5nX2FwYWNoZV9rYWZrYV9vcm
    cBAgM=
    -----END OPENSSH PRIVATE KEY-----
