apiVersion: v1
kind: Secret
metadata:
  name: docker-config-json-secret
  namespace: spring-apache-kafka
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJpb25tYW1hbGlnYWRldiIsInBhc3N3b3JkIjoiZGNrcl9wYXRfVDQxd3VqWUxZcnBpMzZ4RE5OdEdpRlFkTXNrIiwiZW1haWwiOiJpb25tYW1hbGlnYWRldkBnbWFpbC5jb20iLCJhdXRoIjoiYVc5dWJXRnRZV3hwWjJGa1pYWTZaR05yY2w5d1lYUmZWRFF4ZDNWcVdVeFpjbkJwTXpaNFJFNU9kRWRwUmxGa1RYTnIifX19