apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-apache-kafka-consumer
  namespace: spring-apache-kafka
  labels:
    name: spring-apache-kafka-consumer
    app: spring-apache-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spring-apache-kafka-consumer
      app: spring-apache-kafka-consumer
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      name: spring-apache-kafka-consumer
      labels:
        name: spring-apache-kafka-consumer
        app: spring-apache-kafka-consumer
    spec:
      containers:
        - name: spring-apache-kafka-consumer
          image: 202533499956.dkr.ecr.us-east-1.amazonaws.com/spring-apache-kafka-consumer:0.0.0
          imagePullPolicy: Always
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "apache-kafka-0.apache-kafka.spring-apache-kafka.svc.cluster.local:9092"
          ports:
            - containerPort: 8106
      imagePullSecrets:
        - name: docker-config-json-secret