apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-apache-kafka-producer
  namespace: spring-apache-kafka
  labels:
    name: spring-apache-kafka-producer
    app: spring-apache-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spring-apache-kafka-producer
      app: spring-apache-kafka-producer
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      name: spring-apache-kafka-producer
      labels:
        name: spring-apache-kafka-producer
        app: spring-apache-kafka-producer
    spec:
      containers:
        - name: spring-apache-kafka-producer
          image: 431797214645.dkr.ecr.us-east-1.amazonaws.com/spring-apache-kafka-producer:0.0.0
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER_URL
              value: "tcp://localhost:29092"
            - name: CONSUL_HTTP_ADDR
              value: "http://localhost:8500"
          ports:
            - containerPort: 8105
      imagePullSecrets:
        - name: docker-config-json-secret