apiVersion: v1
kind: Service
metadata:
  name: spring-apache-kafka-consumer
  namespace: spring-apache-kafka
  labels:
    name: spring-apache-kafka-consumer
    app: spring-apache-kafka-consumer
spec:
  type: LoadBalancer
  ports:
    - port: 8106
      targetPort: 8106
      protocol: TCP
      name: http
  selector:
    name: spring-apache-kafka-consumer
    app: spring-apache-kafka-consumer