apiVersion: v1
kind: Service
metadata:
  name: spring-apache-kafka-producer
  namespace: spring-apache-kafka
  labels:
    name: spring-apache-kafka-producer
    app: spring-apache-kafka-producer
spec:
  type: LoadBalancer
  ports:
    - port: 8105
      targetPort: 8105
      protocol: TCP
      name: http
  selector:
    name: spring-apache-kafka-producer
    app: spring-apache-kafka-producer